# Site settings
title: Dillon Nye Web CV
email: dillonbnye@gmail.com
url: https://example.github.io
description: "Web CV of Dillon Nye, a PhD candidate in Chemical Biology at Johns Hopkins University."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#ffffff'
  links: '#219ab3'

defaults:
  -
    scope:
      path: "_slides" 
    values:
      layout: "iframe"

collections:
  slides:
    output: true

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google
    url: https://scholar.google.com/citations?user=H__VCTsAAAAJ&hl=en
  - title: linkedin
    url: https://www.linkedin.com/in/dillonbnye/
  - title: github
    url: https://github.com/dillonbnye

# Build settings
markdown: kramdown
permalink: pretty
